# need 4 gpus

project: coconut
save_path: checkpoint
name: cladder-coconut_gen_llama_1B

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 1
max_latent_stage: 6
pad_latent_to_max: True
train_size: 10000
val_size: 100

save_only_improve: False
uniform_prob: 0.0
model_id: "meta-llama/Llama-3.2-1B"
load_model_path: checkpoint/cladder-cot_gen_llama_1B/checkpoint_3
seed: 0
resume: 1
bf16: False
train_path: data/cladder_train_gen.json
val_path: data/cladder_valid_gen.json
reset_optimizer: True
batch_size_training: 4
debug: False
gradient_accumulation_steps: 1
num_epochs: 8
lr: !!float "2e-5"
weight_decay: 0.01
