# need 4 gpus

project: coconut
save_path: checkpoint
name: cladder-coconut-eval_llama_1B

only_eval: True

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 1
max_latent_stage: 6
pad_latent_to_max: True
val_size: 2000

save_only_improve: False
uniform_prob: 0.0
model_id: "meta-llama/Llama-3.2-1B"
load_model_path: checkpoint/cladder-cot_llama_1B/checkpoint_12
seed: 0
resume: 15
bf16: False
train_path: data/cladder_train.json
val_path: data/cladder_test.json
reset_optimizer: True
batch_size_training: 8
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01