# need 4 gpus

project: coconut
save_path: checkpoint
name: gsm-coconut_gpt2

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True
train_size: 10000000
val_size: 100

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: checkpoint/gsm-cot_gpt2/checkpoint_7
seed: 0
resume: 3
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 15
lr: !!float "1e-4"
weight_decay: 0.01