# need 4 gpus

project: coconut
save_path: checkpoint
name: gsm-cot_gpt2

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True
train_size: 10000000
val_size: 100

save_only_improve: True
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 7
lr: !!float "1e-4"
weight_decay: 0.01