_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.6
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size_training:
    value: 32
bf16:
    value: false
c_thought:
    value: 0
coconut:
    value: false
cot:
    value: true
debug:
    value: false
epochs_per_stage:
    value: 1
gradient_accumulation_steps:
    value: 1
load_model_path:
    value: None
lr:
    value: 0.0001
max_latent_stage:
    value: 0
model_id:
    value: openai-community/gpt2
name:
    value: gsm-cot_gpt2
no_cot:
    value: false
no_thoughts:
    value: false
num_epochs:
    value: 7
only_eval:
    value: false
pad_latent_to_max:
    value: true
project:
    value: coconut
reset_optimizer:
    value: false
resume:
    value: 0
save_only_improve:
    value: true
save_path:
    value: checkpoint
seed:
    value: 0
train_path:
    value: data/gsm_train.json
train_size:
    value: 10000000
uniform_prob:
    value: 0
val_path:
    value: data/gsm_valid.json
val_size:
    value: 100
weight_decay:
    value: 0.01
